name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      version_app: 0.0.1

    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: mainmainrl/bot-yggtorrent:${{env.version_app}},mainmainrl/bot-yggtorrent:latest